import Header from '@/app/components/Header'
import Footer from '@/app/components/Footer'

import './styles/globals.scss'


export const metadata = {
  title: 'Evergreen Solar',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="overflow-hidden">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
